### ISSUE TITLE
Problems on pickle

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/speaklater#1]
Apparently lazy gettext thingies cannot be pickled. Fix this.

**Comment by SimonSapin** [comment]
Apparently this is the root cause of the problem discussed [here](http://librelist.com/browser//flask/2012/6/20/re-flask-hard-flask-crash/) and has been fixed in 3ae4bf3083168da6f287acd27522d816ee5bdba1.

All that is needed now is a new release in PyPI: 1.2 still has the bug.

**Comment by mitsuhiko** [comment]
I just pushed a new release to finally fix this.
